CC = cc -arch x86_64 -arch arm64
LDFLAGS = -framework Foundation -lsqlite3
#CFLAGS = -fobjc-arc -g
CFLAGS = -fobjc-arc

OBJ = SQLite3DB.o listKinoppyBooks.o
PROG = listKinoppyBooks
BINDIR = /usr/local/bin

$(PROG): $(OBJ)

.PHONY: clean
clean:
	rm $(OBJ) $(PROG)

.PHONY: install
install:
	install -c $(PROG) $(BINDIR)

### dependency generated by cc -MM *.m
SQLite3DB.o: SQLite3DB.m SQLite3DB.h
listKinoppyBooks.o: listKinoppyBooks.m SQLite3DB.h
